# -*- coding: utf-8 -*-
"""PRODIGY_GA_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaHa3av0krxb_NLLt1T0-CWyvxfUmj3a
"""

import torch
from diffusers import StableDiffusionPipeline
import os

MODEL_ID = "CompVis/stable-diffusion-v1-4"

def load_pipeline():
    print("Loading Stable Diffusion model...")

    if torch.cuda.is_available():
        pipe = StableDiffusionPipeline.from_pretrained(
            MODEL_ID,
            torch_dtype=torch.float16
        ).to("cuda")
    else:
        pipe = StableDiffusionPipeline.from_pretrained(
            MODEL_ID,
            torch_dtype=torch.float32
        )

    pipe.enable_attention_slicing()
    return pipe


def generate_image(pipe, prompt, output_path):
    print(f"Generating image for prompt: {prompt}")

    if torch.cuda.is_available():
        with torch.autocast("cuda"):
            image = pipe(
                prompt,
                num_inference_steps=30,
                guidance_scale=7.5
            ).images[0]
    else:
        image = pipe(
            prompt,
            num_inference_steps=30,
            guidance_scale=7.5
        ).images[0]

    image.save(output_path)
    print(f"Image saved to {output_path}")
    return image


def main():
    os.makedirs("generated_images", exist_ok=True)

    pipe = load_pipeline()

    prompt = "A beautiful sunset over mountains, digital art style"
    output_path = "generated_images/test_image.png"

    generate_image(pipe, prompt, output_path)


if __name__ == "__main__":
    main()