# -*- coding: utf-8 -*-
"""PRODIGY_GA_O3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z05atePd4tZZQY49lAdPhqeT-PRsi0QD
"""

import random
import re

try:
    with open("alice.txt", "r", encoding="utf-8") as file:
        text = file.read()
except FileNotFoundError:
    print("Error: 'alice.txt' not found.")
    exit()

words = re.findall(r"\b\w+\b", text.lower())

if len(words) < 2:
    print("Not enough text to build a Markov chain.")
    exit()


markov_chain = {}
for i in range(len(words) - 1):
    current_word = words[i]
    next_word = words[i + 1]

    if current_word not in markov_chain:
        markov_chain[current_word] = []

    markov_chain[current_word].append(next_word)

start_word = random.choice(list(markov_chain.keys()))
current_word = start_word
generated_text = [current_word]

for _ in range(50):
    if current_word in markov_chain:
        next_word = random.choice(markov_chain[current_word])
        generated_text.append(next_word)
        current_word = next_word
    else:
        break

final_text = " ".join(generated_text)

print("--- Generated Text ---")
print(final_text)